ps Launchy | kill
ps TSVNCache | kill
ps EvernoteClipper | kill
ps BTTray | kill
ps btwdins | kill
ps concentr | kill
ps wfcrun32 | kill
ps jqs | kill
ps SR_Service | kill
ps SR_Watchdog | kill
ps SR_GUI | kill
